name: "OffVocalCleanup"
guid: "02b3d064-2cc9-41d1-b983-894b3fab2c47"
version: "0.1.1"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Scans the Media Library for off-vocal tracks and deletes them."
description: >
  Scans the Media Library for off-vocal tracks and deletes them.
category: "Music"
owner: "Kibouo"
artifacts:
- "Jellyfin.Plugin.OffVocalCleanup.dll"
changelog: >
  0.1.1 - Fixed library selection in settings page and Jellyfin dependencies
